### PR TITLE
Gamepad support

### LINKED ISSUE #59: Junkerships can be controlled by Joypad

### PR DESCRIPTION
**Pull request by Phyoog**
Closes #59

I only have 360 controllers to test this with, so if anyone has anything else, please give it a go. Currently the ship should be controllable with stick or D-pad and any of the face buttons will fire. Should support 4 gamepads, but I only have two to test it with.

http://mocsarcade.github.io/starjunk/81/

[selfie-2](https://github.com/thieman/github-selfies/)

### CODE REVIEW

**Comment by dhowerton** [comment]
img_20160329_155803

Well here I go...

**Comment by dhowerton** [comment]
spawning

My four player skills are weak.

X-Box 360, X-Box One, and PlayStation 4 controllers work.  PlayStation 3 controller does not.  Steam Controller by default is keyboard and mouse on the desktop (pretty sure) so it works but not like you'd want it to.

Switching seamlessly between the analog stick and D-pad seems to be working without any issue for each controller.  Fire button is responsive on all four.

**Comment by s-schmitt** [comment]
Git gud.

**Comment by Phyoog** [comment]
@dhowerton Can you plug in just the non-working PS3 controller, go to http://html5gamepad.com/ and show me what shows up after the webpage recognizes that it's connected?

**Comment by dhowerton** [comment]
Nothing shows up on the site.

Could be a Windows 10 thing.  It shows up under Devices as a PLAYSTATION 3 Controller, but going into the settings there still nothing is detected when you press any buttons.  Have two of them and tried both.  Nada.

Edit: To be fair, I remember having to run third party drivers and software to get the PS3 controller working on PC anyway.

**Comment by Phyoog** [comment]
If that site can't even detect it, then there's nothing we can do to support it using the gamepad API.

**Comment by dhowerton** [comment]
Well, if no one has any comments, I'm going to merge this.

**Pull request merged**
