### PR TITLE
Sinusoidal Power-Ups and CSS Junk Names

### PR DESCRIPTION
**Pull request by codaventure**
Added sinusoidal powerups with easy to adjust amplitude and frequency. Right now in the projectile class it's still playing into the using logic statements over polymorphism, but once all the weapons are merged into master, I plan to fix these code issues.
As far as junk names, I meant to comment on this in @Binome 's PR, but didn't have time. Anyways, I changed them to use CSS/HTML, to help eliminate the soft edges on the font.

https://mocsarcade.github.io/starjunk/97/

### CODE REVIEW

**Comment by Phyoog** [comment]
Game crashes when you pick up junk.

image

**Comment by codaventure** [comment]
Whoops. Forgot to remove `this.destroy()` and accidentally removed some of my code changes from the commit. It should be all set now.

**Comment by Phyoog** [comment]
New crash bug. This was when I got shot. Trying to replicate now.

image

**Comment by Phyoog** [comment]
As for the guns themselves, double sine feels pretty cool and single sine is deliciously frustrating.

**Comment by Phyoog** [comment]
Seems to be a problem with the mineArray, but this code didn't touch it, so I'm not sure why it's only cropping up now.

**Comment by Phyoog** [comment]
Okay, I can replicate the crash in this build by dying while there are mines in existence, but the bug doesn't appear to be present in my local code. We could try pulling the upstream and merging with this to see if that fixes it. Somehow.

**Comment by codaventure** [comment]
Somehow managed to forget to pull from master before making this PR, which explains the mine issues. I should've realized this when I didn't see a title screen... Anyways, everything should be resolved now.

**Comment by Phyoog** [comment]
Crash looks to be fixed. Merging!

**Pull request merged**
