### PR TITLE
Some more PowerUps

### PR DESCRIPTION
**Pull request by s-schmitt**
This adds: 
- Laser
- Piercing Laser
- Super Laser
- Mine

Also adds a parameter to projectile that sets if a projectile is piercing or not.

build: https://mocsarcade.github.io/starjunk/85

### CODE REVIEW

**Comment by Phyoog** [comment]
Seems fine tech wise, but it feels flat. I feel like the lasers should have a color, maybe even sort of pulsate. Also, I feel like they should have a different sound. Maybe shoot-a-1, 2, or 3.

And the mines look... weird. They're just little 2 pixel squares chillin'. Could way maybe make them a tiny bit bigger and visually distinguish them somehow? They feel very drab. I also think they should play an explosion sound when something hits them.

**Comment by s-schmitt** [comment]
Where have you been getting your sounds?

**Comment by Phyoog** [comment]
They're in the source/sounds

**Comment by s-schmitt** [comment]
I mean the actual sound files. Is there some sort of sound database online?

**Comment by Phyoog** [comment]
No, they're already there. I've been using the ones @ehgoodenough supplied.

**Comment by s-schmitt** [comment]
Ok, I will get some changes made to it to make it more exciting.

**Comment by Phyoog** [comment]
[selfie-2](https://github.com/thieman/github-selfies/)

**Pull request closed without merging**
