### PR TITLE
Added high score input/metrics

### LINKED ISSUE #58: Metrics are recorded on Player's Death
Metrics should be sent to Firebase. Make sure to track/display high scores

### PR DESCRIPTION
**Pull request by codaventure**
Closes #58. Making an input system for players to add their names proved more difficult than I anticipated. Right now it's limited to 3 characters, so let me know if this should be increased. Also, Firebase was not tested using prod URL, only a private test URL, so let me know if the setup is ideal.

https://mocsarcade.github.io/starjunk/86

### CODE REVIEW

**Comment by Phyoog** [comment]
Okay... I think there needs to be an indicator of which letter is selected. Underline, blinking, something. I also think we need sound effects for scrolling through the letters and moving left/right in entry. The menu sounds in source/sounds should be fine for this.

Also, gamepad controls aren't working in this build. Did you pull from upstream before you started working on this?

**Comment by codaventure** [comment]
It's all good now. Added the sounds and used CSS animation for the blinking. To fix the gamepad controls I just implemented justDown for them. Let me know about anything else.

**Comment by codaventure** [comment]
It's all good now. Added the sounds and used CSS animation for the blinking. To fix the gamepad controls I just implemented justDown for them. Let me know about anything else. (Build is updated now. Forgot to fix the updated build initially)

**Comment by Phyoog** [comment]
Two big problems here:
1. As-is, if you die while firing a weapon, you're all but guaranteed to submit your initials without realizing anything happened. The best solution I have is for the shoot key/button to advance you through the columns and then submit after the third one. Give people a chance to realize what's happening.
2. Firing the BFG in this build makes you and your projectiles become invisible and insubstantial.

**Comment by codaventure** [comment]
Should be good now. Let me know if anything else needs changed about the score input. As far as the BFG, fire was being called twice, and with justDown it wasn't passed delta. I just changed it where it's called once.

**Comment by Phyoog** [comment]
Updated build?

**Comment by codaventure** [comment]
I could've sworn I did that....
Anyways, it's updated now.

**Comment by Phyoog** [comment]
Much better. Still really easy to accidentally submit the wrong initials, but I'm not sure what else we can do for that. Maybe put in a brief delay where you can't submit until a second has passed? I'll poke around some and see if I can come up with anything, unless someone else has an idea.

**Comment by codaventure** [comment]
I was actually thinking the same thing, but wanted to wait and see what you thought. I'll put about a two second delay on it and reupload the build in a few.

**Comment by codaventure** [comment]
It's on there and I gave it 1.5 second delay. Let me know if this feels right.

**Comment by Phyoog** [comment]
Much better. The only quibble I have left is that in between dying and gaining access to score entry, it says "Press to Join" How much of a burden would it be to change that to "Enter Initials" or something?

**Comment by codaventure** [comment]
I made the message "High Score" mostly because "Enter Initials" looked quirky to me in that font.

**Comment by Phyoog** [comment]
I getcha. And personally, I'm mildly annoyed that A and R are identical in the font

Looks solid now. I'll stop quibbling. Merging!

**Pull request merged**
