### PR TITLE
Shield.

### LINKED ISSUE #61: Weapons - Batch 2
- Shield - Force-field, you still have your pea-shooter 
- Super Laser - one second charge up before a single beam is released **DONE**
- Piercing Laser - laser that can punch through all enemies **DONE**
- Sinusoidal Shot - Sine wave bullets, variable amplitude and frequency **DONE**
- Double Sinusoidal Shot - two waves of the Sinusoidal Shot **DONE**
- Paint Gun - Long cool-down, vomits projectiles **DONE**
- Auto Aim - Hold to lock-on, 1 second acquisition, release to fire **DEPRIORITIZED**
- Mines - lay down up to five mines that move right to left as the screen “scrolls” **DONE**
- Super Mines - mines with much larger explosions **DONE**
- Sword - Short range, directly ahead attack, exact size of the ship directly ahead **DONE**

### PR DESCRIPTION
**Pull request by Phyoog**
Closes #61 Shield added.

Uploaded build with abridged weapon list at https://mocsarcade.github.io/starjunk/103/index.html for easy testing

### CODE REVIEW

**Comment by s-schmitt** [comment]
Tested it with each ship and all of them worked. We just need to remember that the final build should have Pea Shooter at the end of the PowerUp.js so our RNG will be more workable

**Comment by s-schmitt** [comment]
and do we still plan on doing a undefined check before every destroy for the final build?

**Comment by Phyoog** [comment]
Take a look at PowerUp.js, already moved the pea shooter.

Forgot about those. Give me a sec.

**Comment by Phyoog** [comment]
Okay, looks like all the remaining destroy checks that I didn't catch in those commits already got caught with either null checks or only triggering depending on the presence of attributes of the target. So we should be good there.

**Comment by s-schmitt** [comment]
Ok, merging it now.

**Pull request merged**
