### PR TITLE
Sword

### PR DESCRIPTION
**Pull request by s-schmitt**
should despawn and everything now, but who knows at this point.

build: https://mocsarcade.github.io/starjunk/101

### CODE REVIEW

**Comment by Phyoog** [comment]
Nope 
image

**Comment by s-schmitt** [comment]
What did you do to get it to happen?

**Comment by Phyoog** [comment]
I spawned, killed a couple trashbots, and died.

**Comment by s-schmitt** [comment]
Well I guess I didn't push something because it works fine over here. I will upload another build.

**Comment by Phyoog** [comment]
Pull the latest `upstream master` too.

**Comment by s-schmitt** [comment]
https://mocsarcade.github.io/starjunk/101

**Comment by Phyoog** [comment]
Working now. Code looks okay. Merging.

**Pull request merged**
