### PR TITLE
Messed around with the CSS.

### PR DESCRIPTION
**Pull request by ehgoodenough**
starjunk
### List of Changes
- Added thicker underline via borders.
- Fixed the font to be more blocky, so the text-shadows look half-decent.
- Shortened join message to just "press to join", since some players won't be playing on a keyboard!
- Added the join message whenever the <div> for the score is :empty.
- Added a blinking animation that is quickly becoming annoying.
### Playable Link

http://mocsarcade.github.io/starjunk/andrew

### CODE REVIEW

**Comment by ehgoodenough** [comment]
Okay, now it's your turn to tear my code apart, like I've unrelentingly done to yours. I'm afraid it's mostly boring CSS, though. Difficult to read, and even more so to change. I just wanted to clear away some of that boringness for you guys, so you could focus on game logic (and not game ui).

**Comment by Phyoog** [comment]
I like the breaking up of the different players and it looks much more arcade, but you're right about that blink being obnoxious. I get the look you're going for though, and it's very video-gamey. What about having the colored bar stay and just the text blink? That wouldn't look so jarring, but we'd still get that nice "Insert Coin!" vibe.

**Comment by ehgoodenough** [comment]
@Binome: experimented with your ideas. :)

starjunk1

I'm liking this; it's a bit more subtle.
starjunk2

Maybe with an offset delay?
starjunk3

Thoughts?

**Comment by dhowerton** [comment]
I personally prefer just the bar blinking without the timing offset.  It's the least distracting.

**Comment by ehgoodenough** [comment]
Commited to PR, and updated playable link: http://mocsarcade.github.io/starjunk/andrew

**Comment by Phyoog** [comment]
I'm with @dhowerton on this, number two is solid. Playable build looks good. Imma merge this puppy.

**Pull request merged**
