### PR TITLE
Player and enemy explosions

### LINKED ISSUE #57: Trashbots die in a fiery explosion
It must be rad. RAD!

### PR DESCRIPTION
**Pull request by dhowerton**
Closes #57 

First implementation of explosions.  I'm sure we'll be here for a while debating how exactly it should look.  I've been messing with it for a while.  I'll post some GIFs of various other flashier explosions later.

I plan to change the player explosion based on the color of the player ship.

http://mocsarcade.github.io/starjunk/87/

### CODE REVIEW

**Comment by Phyoog** [comment]
I like the disintegration look. Eager to see the flashier ones!

**Comment by dhowerton** [comment]
Well, I would have recorded all my experimentations but Ubuntu on my laptop doesn't like screen recording.  
1. Fiery Wide Pattern
   explosions1
2. Fiery, Fast Random 
   explosions2
3. Fiery, Slow, Tighter Formation (My favorite)
   explosions3

**Comment by Phyoog** [comment]
Of those, I think 2 is the best, but a slightly sped up 3 would be awesome.

**Comment by Phyoog** [comment]
I'm sitting right next to you, and the changes look good. Merging.

**Pull request merged**
