### PR TITLE
Trashbots a Plenty

### PR DESCRIPTION
**Pull request by codaventure**
This got pretty hairy. Also, oops on all the dumb commits. It just kept throwing me errors when I tried to squash them, so I just gave up. Closes issues #42, #43, #44, and #45. Additionally addresses a few bug fixes and performance issues.
Build at: http://mocsarcade.github.io/starjunk/72/

### CODE REVIEW

**Comment by Phyoog** [comment]
Initial thought: could we add something to make the trashbots not spawn when there are 0 players? It gets crazy -really- fast otherwise.

**Comment by codaventure** [comment]
Committed and added to the build. Shouldn't be _too_ crazy now.

**Comment by Phyoog** [comment]
Looks like something borked the score display.

image

**Comment by codaventure** [comment]
I missed an instance of using playerCount in the Score class. I'll fix this this evening.

**Comment by s-schmitt** [comment]
If there are not anymore small fixes anyone sees I can go ahead and pull. It looks fine to me.

**Comment by Phyoog** [comment]
It seems like this pull request has implemented rage mode? That'd mean this PR will also close #46 and #47 which... I mean, if @codaventure wants to close my issues for me, I'm all for it.

**Pull request merged**
