### PR TITLE
MVP - Trashbots respawn

### LINKED ISSUE #15: Junkership can respawn if it's been despawned.
If no junkership exists, wait for any arrow key or space bar to be hit to spawn a new junkership. Be sure this junkership has a new score of just zero.

### LINKED ISSUE #16: Trashbots spawn when the a Trashbot has despawned.
Again, to the right of the screen. Maybe with a random `y`.

### PR DESCRIPTION
**Pull request by Phyoog**
Closes #16: A quick one this time since the only remaining issue, the UI display, is so very different from this one.

So close to the MVP...

[selfie-1](https://github.com/thieman/github-selfies/)

### CODE REVIEW

**Comment by ehgoodenough** [comment]
@Binome, don't forget #16!

**Comment by ehgoodenough** [comment]
Oooh I see; I think you meant #16.

**Comment by Phyoog** [comment]
Yep, helps if I type the correct number. Edited.

**Comment by ehgoodenough** [comment]
Ha ha! Can we get a playable build?

**Comment by Phyoog** [comment]
http://mocsarcade.github.io/starjunk/v0.1.6/

**Pull request merged**
